baseURL = 'http://example.org/'
languageCode = 'nl-nl'
title = 'Geloven Leren'
theme = 'hugo-tufte'
uglyurls = false

[permalinks]
post = '/blog/:filename'
page = '/page/:filename'
portfolio = '/portfolio/:filename'

[params]
subtitle = 'Opinie en tools voor wie begaan is met het katholieke geloof'
showPoweredBy = false
twitter = 'vicmortelmans'
facebook = 'alledaagsgeloven'
copyrightHolder = 'info@gelovenleren.net'

[markup.goldmark.renderer]
unsafe= true

[taxonomies]
  category = "categories"
# -----------------------------------------------------------------------
# Navigation menu 
# -----------------------------------------------------------------------
[[menu.nav]]
  name = "Artikels"
  pre = "<i class='fas fa-home la-lg'></i>"
  weight = -150 
  identifier = "artikels"
  url = "/page/artikels/"
[[menu.nav]]
  name = "Tools"
  pre = "<i class='fas fa-tools la-lg'></i>"
  weight = -140 
  identifier = "tools"
  url = "/page/hulpmiddelen/"
[[menu.nav]]
  name = "Websites"
  pre = "<i class='fas fa-globe la-lg'></i>"
  weight = -130 
  identifier = "websites"
  url = "/page/websites/"
[[menu.nav]]
  name = "Alledaags"
  pre = "<i class='fas fa-dove la-lg'></i>"
  weight = -100 
  identifier = "alledaags"
  url = "https://alledaags.gelovenleren.net/"
[[menu.nav]]
  name = "Bijbel"
  pre = "<i class='fas fa-bible la-lg'></i>"
  weight = -90 
  identifier = "bijbel"
  url = "https://storage.googleapis.com/geloven-leren/books/canisius/index.html"
