baseURL = 'https://gelovenleren.net/'
languageCode = 'nl-nl'
title = 'Geloven Leren'
theme = 'hugo-tufte'
uglyurls = false
googleAnalytics = 'UA-97945493-1'
rssLimit = 10

[permalinks]
post = '/blog/:filename'
page = '/page/:filename'
portfolio = '/portfolio/:filename'

[params]
subtitle = 'Opinie en tools voor wie begaan is met het katholieke geloof'
showPoweredBy = false
twitter = 'AlledaagsG'
facebook = 'alledaagsgeloven'
copyrightHolder = 'info@gelovenleren.net'

[markup.goldmark.renderer]
unsafe = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  tags = "tags"

[related]
threshold = 80
includeNewer = true
toLower = true

[[related.indices]]
name  = "tags"
weight = 100
[[related.indices]]
name  = "date"
weight = 10
pattern = "2006"

# -----------------------------------------------------------------------
# Navigation menu 
# -----------------------------------------------------------------------
[[menu.nav]]
  name = "Artikels"
  pre = "<i class='fas fa-home la-lg'></i>"
  weight = -150 
  identifier = "artikels"
  url = "/page/artikels/"
[[menu.nav]]
  name = "Tools"
  pre = "<i class='fas fa-tools la-lg'></i>"
  weight = -140 
  identifier = "tools"
  url = "/page/hulpmiddelen/"
[[menu.nav]]
  name = "Websites"
  pre = "<i class='fas fa-globe la-lg'></i>"
  weight = -130 
  identifier = "websites"
  url = "/page/websites/"
[[menu.nav]]
  name = "Alledaags"
  pre = "<i class='fas fa-dove la-lg'></i>"
  weight = -100 
  identifier = "alledaags"
  url = "https://alledaags.gelovenleren.net/"
[[menu.nav]]
  name = "Bijbel"
  pre = "<i class='fas fa-bible la-lg'></i>"
  weight = -90 
  identifier = "bijbel"
  url = "https://bijbel.gelovenleren.net/"
[[menu.nav]]
  name = "Zoeken"
  pre = "<i class='fas fa-search la-lg'></i>"
  weight = -80 
  identifier = "zoeken"
  url = "/search/"
# -----------------------------------------------------------------------
# Footer menu 
# -----------------------------------------------------------------------
[[menu.footer]]
  name = "ontvang nieuwe artikels per email"
  pre = "<i class='fas fa-envelope la-lg'></i>"
  url = "https://nieuws.gelovenleren.net/?p=subscribe&id=1"
  weight = 40 
[[menu.footer]]
  name = "rss"
  pre = "<i class='fas fa-rss-square la-lg'></i>"
  url = "/index.xml"
  weight = 20 
