#!/bin/bash
cd public
if [ ! -f "404.html" ]; then
  echo "This doesn't seem to be a valid public folder; exiting"
  exit
fi
USER=$GELOVENLEREN_USER
PASSWORD=$GELOVENLEREN_PASSWORD
SERVER=$GELOVENLEREN_SERVER
lftp -u $GELOVENLEREN_USER,$GELOVENLEREN_PASSWORD @$GELOVENLEREN_SERVER << EOF
mirror -R -n
bye
EOF

