#!/bin/sh
# Usage:
#   ./newpost "This is a new post"
title=$@
slugifytitle=$(slugify "$title")
year=$(date +%Y)
month=$(date +%m)
date=$(date -Iseconds)
path=content/post/$year/$month/$slugifytitle
mkdir -p $path/images
cat > $path/index.md <<EOF
---
title: "$title"
date: $date
categories: 
  - "blog"
tags:
  #- "theologie"
  #- "vrijheid"
  #- "politiek"
  #- "liturgie"
  #- "traditie"
  #- "biecht"
  #- "ethiek"
  #- "aanbidding"
  #- "sacramenten"
  #- "paus"
  #- "vlaanderen"
  #- "opvoeding"
  #- "verbeelding"
  #- "gebed"
  #- "boeken"
  #- "films"
  #- "bijbel"
  #- "woke"
  #- "antwerpen"
  #- "publicaties"
  #- "kerstmis"
  #- "pasen"
  #- "kerkleer"
  #- "onderwijs"
  #- "islam"
  #- "leven"
  #- "synode"
coverImage: ""
---
EOF
gvim $path/index.md &
exit 0
